# This file contains main variables for 3 environments: release, dev/test and acc
# main variables for release environment
rel_srms_page = "https://release-srms.yameo.eu/"
rel_iot_email = "adam.banach85+rel_iot@gmail.com"
rel_iot_password = "Test$123"
rel_test_vessel = "Test Vessel 3"
rel_shipping_agent = "AGENT Adam"
rel_designated_inspector = "INSPECTOR Adam"
rel_csa = "Cargo Test Superintendent"
rel_product_quantity = 1000
rel_bidec = "BIDEC Adam"
rel_depot = "DEPOT Adam"
rel_laycan_date_min = "27-07-2024"
rel_laycan_date_max = "28-07-2024"
rel_dapoa_option_bank = "BANK Adam"
rel_dapoa_quantity = 0.5*rel_product_quantity
rel_ittlc_quantity = 0.3*rel_product_quantity
rel_ittlc_option_bank = rel_dapoa_option_bank
rel_tt_quantity = rel_product_quantity - rel_dapoa_quantity - rel_ittlc_quantity
rel_invoice_ref_number = 1234567890
rel_bidec_email = "adam.banach85+rel_bidec@gmail.com"
rel_bidec_password = "Test$123"
rel_bank_email = "adam.banach85+rel_bank@gmail.com"
rel_bank_password = "Test$123"
rel_depot_email = "adam.banach85+rel_depot@gmail.com"
rel_depot_password = "Test$123"
rel_agent_email = "adam.banach85+rel_agent@gmail.com"
rel_agent_password = "Test$123"
rel_inspector_email = "adam.banach85+rel_inspector@gmail.com"
rel_inspector_password = "Test$123"
rel_master_admin_email = "masteradmin@yameo.eu"
rel_master_admin_password = "Test$123"

# main variables for dev/test environment
dev_srms_page = "https://test-srms.yameo.eu/"
dev_iot_email = "adam.banach85+iot_a_dev@gmail.com"
dev_iot_password = "Test$123"
dev_test_vessel = "Adam Vessel"
dev_shipping_agent = "AGENT Automation"
dev_designated_inspector = "INSPECTOR Automation"
dev_csa = "New Superintendent"
dev_product_quantity = 1000
dev_bidec = "BIDEC Automation"
dev_depot = "DEPOT Automation"
dev_laycan_date_min = "27-07-2024"
dev_laycan_date_max = "28-07-2024"
dev_dapoa_option_bank = "BANK Automation"
dev_dapoa_quantity = 0.5*dev_product_quantity
dev_ittlc_quantity = 0.3*dev_product_quantity
dev_ittlc_option_bank = dev_dapoa_option_bank
dev_tt_quantity = dev_product_quantity - dev_dapoa_quantity - dev_ittlc_quantity
dev_invoice_ref_number = 1234567890
dev_bidec_email = "adam.banach85+bidec_a_dev@gmail.com"
dev_bidec_password = "Test$123"
dev_bank_email = "adam.banach85+bank_a_dev@gmail.com"
dev_bank_password = "Test$123"
dev_depot_email = "adam.banach85+depot_a_dev@gmail.com"
dev_depot_password = "Test$123"
dev_agent_email = "adam.banach85+agent_a_dev@gmail.com"
dev_agent_password = "Test$123"
dev_inspector_email = "adam.banach85+inspector_a_dev@gmail.com"
dev_inspector_password = "Test$123"
dev_master_admin_email = "masteradmin@yameo.eu"
dev_master_admin_password = "Test$123"

# main variables for acc environment
acc_srms_page = "https://acc-srms.yameo.eu/"
acc_iot_email = "adam.banach85+iot_a_acc@gmail.com"
acc_iot_password = "Test$123"
acc_test_vessel = "Test Vessel"
acc_shipping_agent = "AGENT Automation"
acc_designated_inspector = "INSPECTOR Automation"
acc_csa = "Test Agent"
acc_product_quantity = 1000
acc_bidec = "BIDEC Automation"
acc_depot = "DEPOT Automation"
acc_laycan_date_min = "27-07-2024"
acc_laycan_date_max = "28-07-2024"
acc_dapoa_option_bank = "BANK Automation"
acc_dapoa_quantity = 0.5*acc_product_quantity
acc_ittlc_quantity = 0.3*acc_product_quantity
acc_ittlc_option_bank = acc_dapoa_option_bank
acc_tt_quantity = acc_product_quantity - acc_dapoa_quantity - acc_ittlc_quantity
acc_invoice_ref_number = 1234567890
acc_bidec_email = "adam.banach85+bidec_a_acc@gmail.com"
acc_bidec_password = "Test$123"
acc_bank_email = "adam.banach85+bank_a_acc@gmail.com"
acc_bank_password = "Test$123"
acc_depot_email = "adam.banach85+depot_a_acc@gmail.com"
acc_depot_password = "Test$123"
acc_agent_email = "adam.banach85+agent_a_acc@gmail.com"
acc_agent_password = "Test$123"
acc_inspector_email = "adam.banach85+inspector_a_acc@gmail.com"
acc_inspector_password = "Test$123"
acc_master_admin_email = "masteradmin@yameo.eu"
acc_master_admin_password = "Test$123"

# other variables
